### ISSUE TITLE
Comparison to Gitbook?

### ISSUE THREAD

**Issue by jprichardson** [docpress/docpress#1]
So I stumbled upon this by reading over http://rscss.io/. Nice work btw! When I looked at `rscss/gh-pages` I saw `docpress`, so here I am.

The number one question on my mind is how is this different than Gitbook. So it'd be cool if you'd update the readme or add a FAQ or something. Maybe you already have and I missed it, thanks. But it looks awesome!

**Comment by rstacruz** [comment]
mostly [NIH](https://en.wikipedia.org/wiki/Not_invented_here) :)

I wanted to build something that's more focused on building a website that'd offer more degree of control on building nice web documentation.

I still personally recommend Gitbook though—docpress is in its very early stages and Gitbook is a lot more mature.

**Comment by jprichardson** [comment]
> mostly NIH :)

Makes sense :) Well it looks great! I'm excited to see how it progresses :)
