### ISSUE TITLE
EMFILE: too many open files

### ISSUE THREAD

**Issue by Awk34** [docpress/docpress#113]
It seems to get caught up because I have extra `node_modules` installed in a subdirectory (It's a Yeoman generator. It needs its own modules, and any modules used by the generated project for testing purposes)

```bash
MINGW64 $ docpress s

  Docpress
  starting development - ^C to exit

    first build
aNA       livereload
aNA       http://localhost:3000
aNA
    Starting up...
aNA   aNA
  ✗ Failed to read the file at: C:\Users\<user>\Documents\generator-angular-fullstack\test\fixtures\node_modules\gulp-typings\node_modules\delayed-stream\Readme.md

EMFILE: too many open files, open 'C:\Users\<user>\Documents\generator-angular-fullstack\test\fixtures\node_modules\gulp-typings\node_modules\delayed-stream\Readme.md'

    EMFILE: too many open files, open 'C:\Users\<user>\Documents\generator-angular-fullstack\test\fixtures\node_modules\gulp-typings\node_modules\delayed-stream\Readme.md'
    at Error (native)

aNA   aNA   aNA            Running                                 aNB
```

**Comment by knownasilya** [comment]
Getting a similar issue, but at the top level `node_modules`. I think it's the watcher trying to look at too many files (probably all of the files in the dir). I think it might be in the `metalsmith-start` module.

**Comment by knownasilya** [comment]
Actually just adding an ignore to metalsmith seems to fix the issue: https://github.com/docpress/docpress-core/blob/master/lib/ms.js#L23
