### ISSUE TITLE
How to set a domain for Automating GitHub pages ?

### ISSUE THREAD

**Issue by BearD01001** [docpress/docpress#198]
Everytime after commited, the `CNAME` file I created maually will be deleted.
How could I set a domain for documentation website ?

**Comment by knownasilya** [comment]
You'd need to run some sort of copy command that copies something like `myrepo/CNAME` into the folder that gets deployed to your gh-pages branch, e.g. `myrepo/dist/CNAME`. You can do this with npm scripts. See https://www.npmjs.com/package/copyfiles

```sh
copyfiles CNAME dist
```

**Comment by BearD01001** [comment]
@knownasilya Thanks a lot!
