### ISSUE TITLE
Trying to use Docpress

### ISSUE THREAD

**Issue by dborgesr** [docpress/docpress#224]
Hello,
Preface, i'm a javascript noob and have almost never touched it. Given that i'm struggling on how to get the website rendering on github.
I can get the webpage rendering fine w/ docpress locally but when i push to github i instead get a plain markdown layout. 
I'm definitely missing a file or configuration... i'm not sure, i'm kind of at a loss now. The github repo that i'm trying to get working is:
https://github.com/dborgesr/Euplotid
Thank you very much, i would appreciate any tips... i'm about to pull my hair out.

**Comment by knownasilya** [comment]
You should be deploying the output of the `docpress build` command to the ghpages branch.

**Comment by dborgesr** [comment]
Thanks that probably saved me days of awfulness, its all working now, super awesome! thank you!
