### ISSUE TITLE
Support for Multiple Languages

### ISSUE THREAD

**Issue by Purus** [docpress/docpress#225]
What is the best way to support multiple languages? I refer to programming languages.

I am working on a documentation site where I would like to provide snippet in multiple languages for a given question..

How can I organize the content to offer such content?

**Comment by knownasilya** [comment]
This is probably not the best tool for that, see https://github.com/tmcw/docbox

**Comment by kzap** [comment]
Also see https://github.com/GitbookIO/gitbook

**Comment by knownasilya** [comment]
Probably outside of the scope of this library. But you could manually organize your documentation if you wanted to use this library.
