### ISSUE TITLE
Update docpress-core deps to fix security issue.

### ISSUE THREAD

**Issue by ashubham** [docpress/docpress#231]
`Docpress-core` was recently updated with a security vulnerability fix:

https://github.com/docpress/docpress-core/commit/3cc193cd2238a317d2488a52b42b5113bc73e9f8

Please update the `docpress` repo to use the updated `docpress-core`.

**Comment by knownasilya** [comment]
Yeah, I just updated core. Will be doing more updates soon.

**Comment by knownasilya** [comment]
wip: https://github.com/rstacruz/metalsmith-start/pull/146 feel free to jump in if you know what the issue might be
