### ISSUE TITLE
How to insert an image?

### ISSUE THREAD

**Issue by mittalyashu** [docpress/docpress#232]
`![Work together and collaborate](images/work-together-and-collaborate.png)`

When I try to add the image, got this error.

```
(node:5648) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 46): Error: README.md: Unknown reference 'images/work-together-and-collaborate.png'
```

**Comment by knownasilya** [comment]
Sounds like the path is incorrect. Is the images folder in the "docs" folder?

**Comment by mittalyashu** [comment]
Nope, it is in the root of the directory.

**Comment by knownasilya** [comment]
If for some reason you can't move them to the `docs` folder, then you can try a relative url, I.e. `../images`

**Comment by mittalyashu** [comment]
I was trying to start from the scratch again and this time, while installing I got this error.

![image](https://user-images.githubusercontent.com/29014463/35500874-03c915cc-04fe-11e8-9edf-9747878066c6.png)

Here's the NPM Debug log file.
[npm-debug.log](https://github.com/docpress/docpress/files/1672792/npm-debug.log)

**Comment by blindedbymscience** [comment]
I was running into the same issue at first.  Then I added an images folder at the same level as my pages (inside docs) and was able to add images successfully: i.e. ![text](images/myimage.jpg)

**Comment by knownasilya** [comment]
Gonna close this, since images inside the docs folder do work. If those don't work for you, please open another issue.
