### ISSUE TITLE
Mobile: 'Next' overlay shadows button

### ISSUE THREAD

**Issue by zeroby0** [docpress/docpress#234]
Here is an example.
![img_3008](https://user-images.githubusercontent.com/16903044/38789258-ce220b64-4156-11e8-914c-6f8921d65b99.png)

This can usually be solved by adding a padding to the div. In my case, 

`<div class="body page-getting-startedquickstart" style="padding-bottom: 80px">`
on page http://docpress.github.io/getting-started/quickstart.html helped.

I'll make a pull request if I get time.

Thank you.

**Comment by knownasilya** [comment]
Seems to be solved.
