### ISSUE TITLE
Build failed - did you forget to load/include a language module?

### ISSUE THREAD

**Issue by dingo-d** [docpress/docpress#250]
When I serve my docs using `docpress s` everything works, and I can see my docs on `http://localhost:3000`, however, when I try to build it using `docpress b` I get

```
Could not find the language '', did you forget to load/include a language module?
Could not find the language '', did you forget to load/include a language module?
Could not find the language '', did you forget to load/include a language module?
Could not find the language '', did you forget to load/include a language module?
Could not find the language '', did you forget to load/include a language module?
```

There's nothing in the documentation about the language module.

My `docpress.json` file looks like this:

```json
{
  "github": "infinum/eightshift-frontend-libs",
  "docs": "docs",
  "lang": "en",
  "markdown": {
    "typographer": true,
    "plugins": {
      "decorate": {}
    }
  },
  "plugins": {
    "docpress-core": {},
    "docpress-base": {}
  }
}
```

**Comment by knownasilya** [comment]
Are you using triple backticks anywhere in your markdown? Maybe syntax highlighting is having an issue because there is no syntax type?

**Comment by dingo-d** [comment]
Yes I am almost everywhere where I need to add bigger code block. Should I 'typehint' event empty backticks?

**Comment by knownasilya** [comment]
Yeah seems like it's highlight.js which adds highlighting. https://github.com/highlightjs/highlight.js/blob/a77a132904ac93fdc48ba73891d4cd8260824e71/src/highlight.js#L53

Weird, because usually it just works.

**Comment by dingo-d** [comment]
I'll check the `hightlight-js`, maybe I added a language in a wrong way 🤷‍♂ 

Thanks for extremely quick response 😄 👍

**Comment by dingo-d** [comment]
I've added `shell` to regular code blocks, and I had one `javascript` instead of `js`, and after I've changed this it worked. Thanks for helping out!

**Comment by knownasilya** [comment]
Awesome 👍
