### ISSUE TITLE
Embedded examples don't load

### ISSUE THREAD

**Issue by dmvaldman** [docpress/docpress#27]
I have some codepen examples I embed into my documentation, and they'll load on a browser refresh, but not when clicking from one page to the next. I changed the "DOMContentLoaded" listener to "load" instead, and that fixed it, but maybe there's a better way.

**Comment by rstacruz** [comment]
yeah, that's cause we're using [pjax](https://www.npmjs.com/package/pjax) to load new pages in place, making the experience faster as you browse though docs. your workaround is indeed the way it should be done.
