### ISSUE TITLE
Docpress local install funk

### ISSUE THREAD

**Issue by 1vasari** [docpress/docpress#3]
# Description

I'm trying to use docpress in my project, however, I've run into a weird issue with installing it locally in my project. After installing it globally (`npm install docpress -g`) everything works fine. After installing it locally (`npm install docpress --save-dev`), however, when running it, it exits immediately, producing no output.
# Versions of my stuff

OS: Windows 10
node: 4.1.1
npm: 3.5.0
docpress: 0.6.6
# Steps

``` bash
git clone https://github.com/1vasari/docpress-issue
cd docpress-issue
npm i
docpress s
```

**Note**: removing `node_modules` makes it work again. Putting them back breaks it.

**Comment by rstacruz** [comment]
thanks for the very detailed report!

**Comment by rstacruz** [comment]
I've released v0.6.7. This doesn't actually fix the issue, but it should throw an error in this case. Can you try it out and see what error shows up for you?

**Comment by rstacruz** [comment]
Can't reproduce your here, btw—but I did spot what is likely happening; when `node_modules/.bin/docpress` exists, running `docpress` will try to run that instead. when this fails, it dies silently... it should now show you the error.

**Comment by 1vasari** [comment]
Ah yes, I got an error:

:fire:

![It errors!](http://puu.sh/lInfY/d9fb4f6029.png)

**Comment by rstacruz** [comment]
ah! windows!

**Comment by rstacruz** [comment]
okay, v0.6.8 is out and it should fix those issues on Windows. hope that does it :)

**Comment by 1vasari** [comment]
Another issue. :sob: 

Seems like another issue with delegating to locally installed versions of the module.

![Windows :(](http://puu.sh/lIZiH/5c1791f3af.png)

I would suggest, if I may, that using a module like [liftoff](https://www.npmjs.com/package/liftoff) would simplify this process - [Gulp uses it](https://github.com/gulpjs/gulp/blob/master/bin/gulp.js#L21).

**Comment by rstacruz** [comment]
haha oh god i dont even know where that's coming from

**Comment by rstacruz** [comment]
```case `uname` in``` looks like something out of a shell script though. i assume node for windows makes bin stubs in node_modules/.bin that are shell scripts?

**Comment by rstacruz** [comment]
okay, try again :)

**Comment by rstacruz** [comment]
This looks like a problem with delegate_bin.js not being compatible with
Windows. Thanks for the report!

Can you do this and tell us the output?

    ls node_modules/.bin

**Comment by rstacruz** [comment]
Ah nevermind on the ls snippet - I think I know what's up haha
