### ISSUE TITLE
Search is not working in generated pages

### ISSUE THREAD

**Issue by wsanter** [docpress/docpress#38]
Hi, Loving docpress so far. 
Only one small issue, Search is not working in generated pages. Or what is the little spyglass upper left for?

**Comment by rstacruz** [comment]
haha.. a search that was never fully implemented, sorry :(

**Comment by knownasilya** [comment]
@rstacruz are you fine with removing the module/icon for now?

**Comment by rstacruz** [comment]
Yeah, I never got around fully implementing it, let's remove it

**Comment by Purus** [comment]
Are there any plans to implement search feature? For me, it's an important feature.
