### ISSUE TITLE
This project is awesome, what are your plans?

### ISSUE THREAD

**Issue by kimmobrunfeldt** [docpress/docpress#48]
Hi,

I really like the work you've put into this project. I've been wanting for something like this for long! I like the theme and everything in this project. What are your plans in with this project? It seems that you are not very actively developing it anymore. Have you found another tool which does the same job?

**Comment by rstacruz** [comment]
It's mostly complete haha that's why I haven't worked on it much. Will
answer the rest later.

**Comment by knownasilya** [comment]
Myself and @Kikobeats have been added to the org and we've been making fixes and improvements lately as well.

**Comment by knownasilya** [comment]
Closing this, since it's not really actionable.
