### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by apathetic** [docpress/docpress#55]
Hi, when running this locally I encounter the following issue: 

```
Failed to read the file at: ...../node_modules/.bin/mkdirp
ENOENT: no such file or directory, stat '..../node_modules/.bin/mkdirp'  

```
I'm running docpress locally:

```
$ npm i docpress --save-dev
$ node_modules/.bin/docpress serve
```

Manually installing the mkdirp package seems to cure the issue for me.

**Comment by knownasilya** [comment]
Feel free to reopen if the issue is still there for the latest version.
